Repository LNP-WG/lnp-node, pull requests merged in 2020-11, with the labels that each got.

#23 fix home path resolution at data_dir creation
  src/.opts.rs.swp
  src/opts.rs
Labels: bug

#27 CI: add crate publication workflow
  .github/workflows/publication.yml
Labels: enhancement

#29 Update Alpha4 demo readme file
  doc/demo-alpha.4/README.md
Labels: documentation
